apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: kafka
  
  template:
    metadata:
      name: kafka
      labels: 
        app: kafka
    spec:
      containers:
        - name: kafka
          image: docker.io/bitnami/kafka:3.5
          env:
            - name: KAFKA_CFG_NODE_ID
              value: "0"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: controller,broker
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: 0@kafka:9093
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092,CONTROLLER://:9093
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
          volumeMounts:
            - name: volume-kafka
              mountPath: /bitnami/kafka
      # initContainers:
      #   - name: take-data-dir-ownership
      #     image: alpine:3
      #     command: ["sh","-c","mkdir -p /data && chown -R 1001:1001 /data"]
      #     volumeMounts:
      #     - name: volume-kafka
      #       mountPath: /data
      volumes:
        - name: volume-kafka
          emptyDir:
            sizeLimit: 4Gi
---


apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - name: tcp-1
      protocol: TCP
      port: 9092
    - name: udp-1
      protocol: UDP
      port: 9092
    - name: tcp-2
      protocol: TCP
      port: 9093
    - name: udp-2
      protocol: UDP
      port: 9093
  selector:
    app: kafka
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-np
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - name: tcp-1
      protocol: TCP
      port: 9092
      nodePort: 30092
    - name: udp-1
      protocol: UDP
      port: 9092
      nodePort: 30092
    - name: tcp-2
      protocol: TCP
      port: 9093
      nodePort: 30093
    - name: udp-2
      protocol: UDP
      port: 9093
      nodePort: 30093
