apiVersion: apps/v1
kind: Deployment
metadata:
  name: state-redis
  labels:
    app: state-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: state-redis
  template:
    metadata:
      name: state-redis
      labels:
        app: state-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine

---

apiVersion: v1
kind: Service
metadata:
  name: state-redis
  labels:
    app: state-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector: 
    app: state-redis
  type: ClusterIP
