processorConfigs: 
  - parentDirectory: /home/svt/go/src/github.com/ttraveller7/invokerlib-examples/word_count
    files: 
    - go.mod
    - go.sum
    - splitter.go
    entryPoint: "SplitterHandler"
    name: "splitter"
    numOfWorker: 3
    inputKafkaConfig: 
      address: "kafka:9092"
      topic: "word_count_source"
    outputConfig: 
      defaultTopicPartitions: 3
  - parentDirectory: /home/svt/go/src/github.com/ttraveller7/invokerlib-examples/word_count
    files: 
    - go.mod
    - go.sum
    - counter.go
    entryPoint: "CounterHandler"
    name: "counter"
    numOfWorker: 1
    inputProcessor: "splitter"
    outputConfig: 
      defaultTopicPartitions: 0

globalKafkaConfig: 
  address: "kafka:9092"
  initialTopics:
  - topic: "word_count_source"
    partitions: 3

globalStoreConfig:
  redisConfigs:
  - name: "state-redis"
    address: "state-redis:6379"
