processorConfigs: 
  - parentDirectory: /home/svt/go/src/github.com/ttraveller7/invokerlib-examples/word_count
    files: 
    - go.mod
    - go.sum
    - splitter.go
    entryPoint: "SplitterHandler"
    name: "splitter"
    numOfWorker: 1
    inputKafkaConfig: 
      address: "kafka:9092"
      topic: "word_count_source"
    outputConfig: 
      defaultOutputTopicPartitions: 1
  - parentDirectory: /home/svt/go/src/github.com/ttraveller7/invokerlib-examples/word_count
    files: 
    - go.mod
    - go.sum
    - counter.go
    entryPoint: "CounterHandler"
    name: "counter"
    numOfWorker: 1
    inputProcessor: "splitter"
    outputConfig: 
      defaultOutputTopicPartitions: 0

globalKafkaConfig: 
  address: "kafka:9092"
