processorConfigs: 
  - parentDirectory: /home/svt/go/src/ttraveller7/invokerlib/example_word_count
    files: 
    - go.mod
    - go.sum
    - splitter.go
    name: "splitter"
    numOfWorker: 1
    inputKafkaConfig: 
      address: ""
      topic: ""
    outputConfig: 
      defaultOutputTopicPartitions: 1
  - directory: /home/svt/go/src/ttraveller7/invokerlib/example_word_count
    files: 
    - go.mod
    - go.sum
    - counter.go
    name: "counter"
    numOfWorker: 1
    inputKafkaConfig: 
      address: ""
      topic: ""
    outputConfig: 
      defaultOutputTopicPartitions: 0

globalKafkaConfig: 
  address: "kafka:9092"
